import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./contexts/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        rubik: ['Rubik', 'sans-serif'],
      },
      colors: {
        "surface": "#170f27",
        "secondary-container": "#00e3fd",
        "on-primary-container": "#570032",
        "secondary": "#bdf4ff",
        "on-surface": "#eaddff",
        "outline": "#a98893",
        "surface-container": "#231b34",
        "error": "#ffb4ab",
        "on-tertiary": "#412d00",
        "on-secondary": "#00363d",
        "tertiary-fixed": "#ffdea8",
        "secondary-fixed-dim": "#00daf3",
        "on-error": "#690005",
        "primary-container": "#ff45a3",
        "on-background": "#eaddff",
        "primary": "#ffb0cd",
        "surface-container-high": "#2e263f",
        "on-primary": "#640039",
        "error-container": "#93000a",
        "secondary-fixed": "#9cf0ff",
        "tertiary-fixed-dim": "#ffba20",
        "surface-container-lowest": "#120a21",
        "surface-container-highest": "#39304a",
        "surface-container-low": "#1f1730",
        "on-primary-fixed": "#3e0022",
        "background": "#170f27",
        "outline-variant": "#5a3f49",
        "surface-bright": "#3e354f",
        "tertiary": "#ffba20",
        "primary-fixed": "#ffd9e4",
        "on-secondary-fixed": "#001f24",
        "surface-variant": "#39304a",
        "on-secondary-container": "#00616d",
        "surface-tint": "#ffb0cd",
        "inverse-surface": "#eaddff",
        "on-surface-variant": "#e1bdc8",
        "tertiary-container": "#bc8700",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-container": "#392600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "margin-sm": "1rem",
        "gutter": "1.5rem",
        "space-xs": "0.375rem",
        "space-xl": "2.5rem",
        "margin": "1.5rem",
        "margin-lg": "3rem",
        "space-md": "1.25rem",
        "space-lg": "1.75rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem",
      },
    },
  },
  plugins: [],
};

export default config;
